name: Create readme from template
on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch:  #runs manually  
  push:
    branches:
      - master
jobs:
  greet:
    runs-on: ubuntu-latest 
    steps:   
     - uses: actions/checkout@v2   
       with:      
        fetch-depth: 0    
     - name: Generate README.md      
       uses: teoxoy/profile-readme-stats@v1     
       with:       
        token: ${{ secrets.GIT_USER_STATS }}    
     - name: Update README.md     
       run: |     
        if [[ "$(git status --porcelain)" != "" ]]; then        path: ~/.cache/pip
        git config user.name github-actions[bot]        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
