name: Update activity
on: 
    schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
workflow_dispatch:
  push:
    branches:
      - master

jobs:
  gadpp_job:
    runs-on: ubuntu-latest
    name: Update GitHub Profile Page
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: GADPP
        uses: umutphp/github-action-dynamic-profile-page@v2
        id: gadpp
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github-username: NihalV123
          user-email: nhlvcam@gmail.com


