name: Update README

on:
  schedule:
    - cron: '0 */3 * * *' # runs every 3 hours
  workflow_dispatch: #runs manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: khaosdoctor/blog-post-workflow@master
        with:
          comment_tag_name: DEVTO
          feed_list: "https://dev.to/feed/khaosdoctor"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: MEDIUM
          feed_list: "https://medium.com/feed/@khaosdoctor"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: BLOG
          feed_list: "https://blog.lsantos.dev/rss"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: FCC
          feed_list: "https://www.freecodecamp.org/news/author/_staticvoid/rss"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCDCHcqyeQgJ-jVSd6VJkbCw" 
