name: Update README

on:
  schedule:
     - cron: '0 */3 * * *' # runs every 3 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activity

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ 5f2921d4b87fc1ba653b9cd0c5101828ed33828b  }}
        with:
          COMMIT_MSG: 'PR activity updated!'
