name: today's Waka Stats 

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch:  # runs manually

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE : "True"
          SHOW_PROFILE_VIEWS : "True"
          SHOW_COMMIT : "True"
          SHOW_DAYS_OF_WEEK : "True"
          SHOW_LANGUAGE : "True"
          SHOW_OS : "True"
          SHOW_PROJECTS : "True"
          SHOW_EDITORS : "True"
          SHOW_LOC_CHART : "True"
          LOCALE: "en"



